package com.bing.mymvpdemo.data.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bing.mymvpdemo.data.db.entity.Person;
import com.bing.mymvpdemo.data.db.entity.test;
import com.bing.mymvpdemo.data.db.entity.User;

import com.bing.mymvpdemo.data.db.greendao.PersonDao;
import com.bing.mymvpdemo.data.db.greendao.testDao;
import com.bing.mymvpdemo.data.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig testDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PersonDao personDao;
    private final testDao testDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        testDaoConfig = daoConfigMap.get(testDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        testDao = new testDao(testDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(test.class, testDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        testDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public testDao getTestDao() {
        return testDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
